### ISSUE TITLE
LTO

### ISSUE THREAD

**Issue by nu8** [curl/curl-for-win#13]
is it possible to do LTO? I tried like this:

~~~
CURL_CFLAG_EXTRAS=-flto
~~~

but it creates an error:

~~~
strip: sta12956/altsvc.o: plugin needed to handle lto object
~~~

I also tried like this:

~~~
CURL_CFLAG_EXTRAS='-flto -ffat-lto-objects'
~~~

but the size explodes. I also messed with these and no luck:

~~~
AR=gcc-ar
RANLIB=gcc-ranlib
~~~

**Comment by vszakats** [comment]
I've found LTO to be too much an effort to maintain, even when building with gcc only. Support got removed in 8f605c624349dbe5fb07c2a521db52d139856aac for OpenSSL (also in response to a general security warning from an OpenSSL maintainer.)

Now gcc is only used with OpenSSL, the rest is LLVM/clang, which likely doesn't make it simpler do to a full curl LTO build, though the (untested) option is still there to revert to gcc.

LTO used to make the build process fragile, due to the LTO file-formats and options being in flux, packages generally not focusing on that build mode and all the bugs that surfaced along the process.

The performance benefit in case of curl would likely be unnoticeable, unlike file size growth, as you also spotted. Last time I tried, `-ffat-lto-objects` was required for mingw gcc editions. It's possible to fine tune binary size to some extent, but the result will always be larger than a non-LTO build due to the globally inlined functions.

So, an interesting challenge, likely doable, with likely downsides. For this repo it's out of scope due to these reasons.
