### ISSUE TITLE
LTO support

### ISSUE THREAD

**Issue by Andarwinux** [curl/curl-for-win#59]
Clang ThinLTO now work fine on Linux and MinGW, just add `-flto=thin`, but there is currently an issue where executing strip with static libraries built with LTO may fail, which makes it impossible to build curl with LTO/CFI (`-fsanitize=cfi`). Therefore, we should remove strip from the build script and strip only for curl executables or dynamic libraries.

**Comment by vszakats** [comment]
I've made a journey with LTO many years ago, and the experience still hurts. What hurt most was the LTO metadata using a format that wasn't compatible between toolchain releases, requiring to rebuild every object after compiler updates. This isn't an issue in CI, but it is burden for local testing. Another issue was sensitivity to 3rd party issues (e.g. bumped into an OpenSSL function that was declared and defined differently, surfacing only when doing LTO). And slow link times.

Things may have improved and it wasn't ThinLTO yet back then, so we might give it a cautioius retry!

But, we do have to strip static libs to remove the non-reproducible bits from them, because we ship them in the curl-for-win package.

It seems CI bumped into this right away:
```
+ llvm-strip-17 --enable-deterministic-archives --strip-debug _a64-linux-gnu/usr/lib/libz.a
llvm-strip-17: error: '_a64-linux-gnu/usr/lib/libz.a(adler32.c.o)': The file was not recognized as a valid object file
```
https://github.com/curl/curl-for-win/actions/runs/7128972278/job/19411993913#step:3:2843

Do you see any way around this? Enabling this for a future LLVM version perhaps?

**Comment by vszakats** [comment]
Here's a test build with ThinLTO:
https://github.com/curl/curl-for-win/actions/runs/7131676251

The results mirror my memories: All binaries grew, by a large margin.
Static libs are not as larger as I remember with fat LTO, but still add
to the already inflated sizes (after `--gc-sections`).

I agree with you that for curl, the bottleneck is not here. It's rather in
the network code, protocol implementation (which has seen a lot
of streamlining this year, and more is coming up.), DNS resolver and
parallelization.

This and the test binaries are not convincing me that curl-for-win
is benefitting from LTO.

There was also a fallout with macOS + llvm where the linker is [missing](https://github.com/curl/curl-for-win/actions/runs/7131041425/job/19418771861#step:3:11956)
some LibreSSL functions. Here's the patch if you'd like to experiment:

```diff
--- a/_build.sh
+++ b/_build.sh
@@ -973,6 +973,11 @@ build_single_target() {
     fi
   fi
 
+  if [[ "${_CC}" = 'llvm' && ( "${_OS}" != 'mac' || "${_TOOLCHAIN}" = 'llvm-apple' ) ]]; then
+    _CFLAGS_GLOBAL+=' -flto=thin'
+    _CXXFLAGS_GLOBAL+=' -flto=thin'
+  fi
+
   # curl recommended options to reduce binary size:
   # https://github.com/curl/curl/blob/master/docs/INSTALL.md#reducing-size
 
@@ -1309,6 +1314,7 @@ build_single_target() {
     _STRIP_LIB="${_STRIP_BIN}"
     _STRIPFLAGS_LIB='--enable-deterministic-archives --strip-debug'
   fi
+  _STRIP_LIB='echo'
   export _OBJDUMP="${_BINUTILS_PREFIX}objdump${_BINUTILS_SUFFIX}"
   export _READELF="${_BINUTILS_PREFIX}readelf${_BINUTILS_SUFFIX}"  # symlink to llvm-readobj in llvm
   if [ "${_OS}" = 'win' ]; then
```
