### ISSUE TITLE
effects of going nroffless

### ISSUE THREAD

**Issue by bagder** [curl/curl-for-win#67]
The curl-cmake.sh and curl-autotool.sh currently both check for `docs/curl.1` to make decisions.

Two things about this:

1. The `curl.1` file is no longer used as source for making the `tool_hugehelp.c` file. It instead uses the `curl.txt` ASCII version as source - but that is not shipped in the tarball.
2. The `curl.1` file now lives as `docs/cmdline-opts/curl.1` in the tarball

**Comment by vszakats** [comment]
Thanks for the heads up!

Just posted this: https://github.com/curl/curl/issues/13028#issuecomment-1981918104
And plan to merge this patch tested earlier today: https://github.com/curl/curl-for-win/commit/d51b94232a695d737607f69294e979a6e79e1fe4

My initial build perf measurements were wrong, and it turns out that building the manual takes no considerable time.
It means the manual hack involving `curl.1` checks are safe to delete now. I've set `SOURCE_DATE_EPOCH`
earlier, but that's probably also unnecessary now, given that curl-for-win doesn't distribute `curl.1`.

Does that sound OK?

**Comment by bagder** [comment]
Sounds great!
